"""agregar tabla material_usage_details

Revision ID: e7fb4edbdb4d
Revises: 8a28d2bec212
Create Date: 2026-07-12 19:13:32.695349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7fb4edbdb4d'
down_revision: Union[str, Sequence[str], None] = '8a28d2bec212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Se borra primero la tabla vieja porque su FK impide cambiar el tipo de materials.id
    op.drop_table('material_project_details')

    # Ahora sí se puede cambiar el tipo, sin la FK vieja bloqueando
    op.alter_column('materials', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=5),
               existing_nullable=False)

    op.create_table('material_usage_details',
    sa.Column('project_id', sa.String(length=5), nullable=False),
    sa.Column('material_id', sa.String(length=5), nullable=False),
    sa.Column('used_quantity', sa.Float(), nullable=False),
    sa.Column('measurement_unit', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('project_id', 'material_id')
    )
    op.alter_column('account_statements', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('account_statements', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('clients', 'client_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('clients', 'client_company_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('clients', 'client_phone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('clients', 'client_email',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               existing_nullable=True)
    op.alter_column('materials', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('materials', 'specifications',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=False)
    op.alter_column('payrolls', 'payroll_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('payrolls', 'worker_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('payrolls', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('payrolls', 'payroll_fortnight_period',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('projects', 'client_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'quote_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('projects', 'project_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('projects', 'project_location',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('projects', 'project_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('quotes', 'quote_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quotes', 'client_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('quotes', 'quote_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'unit',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'notes',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
    op.alter_column('worker_assignments', 'assignment_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('worker_assignments', 'worker_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('worker_assignments', 'project_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('workers', 'worker_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.alter_column('workers', 'worker_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workers', 'worker_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('workers', 'worker_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('worker_assignments', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('worker_assignments', 'worker_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('worker_assignments', 'assignment_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'notes',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('technical_measurements', 'unit',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('technical_measurements', 'id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('quotes', 'quote_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('quotes', 'client_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('quotes', 'quote_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('projects', 'project_status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('projects', 'project_location',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'project_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('projects', 'quote_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('projects', 'client_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('projects', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payrolls', 'payroll_fortnight_period',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('payrolls', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payrolls', 'worker_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('payrolls', 'payroll_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('materials', 'specifications',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('materials', 'description',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('clients', 'client_email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('clients', 'client_phone',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('clients', 'client_company_name',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('clients', 'client_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'notes',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('biweekly_requests', 'status',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('biweekly_requests', 'id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('account_statements', 'project_id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('account_statements', 'id',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)

    # Se borra primero la tabla nueva porque su FK usa materials.id como String
    op.drop_table('material_usage_details')

    # Ahora sí se puede revertir el tipo, sin la FK nueva bloqueando
    op.alter_column('materials', 'id',
               existing_type=sa.String(length=5),
               type_=sa.INTEGER(),
               existing_nullable=False)

    op.create_table('material_project_details',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('material_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('unit_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('material_project_details_material_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('material_project_details_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('material_project_details_pkey'))
    )
    # ### end Alembic commands ###